language: php

sudo: false

# DEPLOY: This "ignore" directive travis from processing branches with a -built
# suffix, thus avoiding endless loops
if: branch =~ ^.*(?<!-built)$

# If you specify `script` directive, Travis will try to run PHPUnit
# Replace this with whatever tests you wish, or leave in place if
# you only want to run the deploy.
script: echo "No tests"

# DEPLOY: If you want to only run the deploy script when tests
# pass, use `after_success` instead, you will need to add a
# `script` directive with some tests if you want to do this :)
after_script:
  - bash <(curl -D /tmp/headers-1.txt -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy-travis-prepare.sh") && bash <(curl -D /tmp/headers-2.txt -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
